version: '3'

services:
  api:
    container_name: api_secure
    build: ./api
    ports:
      - "5000:5000"
  client:
    container_name: client_secure
    build: ./client
    depends_on:
      - api
    ports:
      - "5001:5000"